Repository LovelySejong/MTVS_3rd_BE, pull requests merged in 2024-09, with the labels that each got.

#5 [Feat] Member
  .gitignore
  src/main/java/com/mtvs/sejong/_core/config/SecurityConfig.java
  src/main/java/com/mtvs/sejong/_core/jwt/JWTTokenFilter.java
  src/main/java/com/mtvs/sejong/_core/jwt/JWTTokenProvider.java
  src/main/java/com/mtvs/sejong/_core/utils/CustomUserDetail.java
  src/main/java/com/mtvs/sejong/_core/utils/SecurityUtils.java
  src/main/java/com/mtvs/sejong/user/controller/UserController.java
  src/main/java/com/mtvs/sejong/user/domain/Authority.java
  src/main/java/com/mtvs/sejong/user/domain/User.java
  src/main/java/com/mtvs/sejong/user/dto/UserRequestDTO.java
  src/main/java/com/mtvs/sejong/user/dto/UserResponseDTO.java
  src/main/java/com/mtvs/sejong/user/repository/UserRepository.java
  src/main/java/com/mtvs/sejong/user/service/UserService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#8 Feat 3
  build.gradle
  src/main/java/com/mtvs/sejong/SejongApplication.java
  src/main/java/com/mtvs/sejong/_core/config/WebClientConfig.java
  src/main/java/com/mtvs/sejong/_core/error/exception/InternalServerException.java
  src/main/java/com/mtvs/sejong/_core/utils/WebClientUtil.java
  src/main/java/com/mtvs/sejong/question/application/controller/RecommendController.java
  src/main/java/com/mtvs/sejong/question/application/dto/RecommendRequestDTO.java
  src/main/java/com/mtvs/sejong/question/application/dto/RecommendResponseDTO.java
  src/main/java/com/mtvs/sejong/question/domain/aggregate/Question.java
  src/main/java/com/mtvs/sejong/question/domain/repository/QuestionRepository.java
  src/main/java/com/mtvs/sejong/question/domain/service/QuestionService.java
  src/main/java/com/mtvs/sejong/question/openfeign/AIResponseDto.java
  src/main/java/com/mtvs/sejong/question/openfeign/QuestionFeignClient.java
  src/main/resources/application.yml
  src/test/java/com/mtvs/sejong/question/domain/service/QuestionTests.java
Labels: ✨ Feature

#9 [Feat 2] - localServerStart
  src/main/java/com/mtvs/sejong/SejongApplication.java
  src/main/java/com/mtvs/sejong/_core/config/SecurityConfig.java
Labels: 🌏 Deploy, ✨ Feature

#10 [Feat] PlayLog entity 구현
  src/main/java/com/mtvs/sejong/_core/utils/SecurityUtils.java
  src/main/java/com/mtvs/sejong/playlog/controller/PlayLogController.java
  src/main/java/com/mtvs/sejong/playlog/domain/PlayLog.java
  src/main/java/com/mtvs/sejong/playlog/dto/PlayLogRequestDTO.java
  src/main/java/com/mtvs/sejong/playlog/repository/PlayLogRepository.java
  src/main/java/com/mtvs/sejong/playlog/service/PlayLogService.java
  src/test/java/com/mtvs/sejong/playlog/PlayLogServiceTest.java
Labels: ✨ Feature

#12 Refactor: PlayLog field 수정
  src/main/java/com/mtvs/sejong/playlog/domain/PlayLog.java
  src/main/java/com/mtvs/sejong/playlog/dto/PlayLogRequestDTO.java
  src/main/java/com/mtvs/sejong/playlog/service/PlayLogService.java
  src/test/java/com/mtvs/sejong/playlog/PlayLogServiceTest.java
Labels: 🔨 Refactor

#13 [test/playlog] XR 통신 테스트
  src/main/java/com/mtvs/sejong/SejongApplication.java
  src/main/java/com/mtvs/sejong/_core/config/SecurityConfig.java
  src/main/java/com/mtvs/sejong/_core/filter/CORSFilter.java
  src/main/java/com/mtvs/sejong/_core/jwt/JWTTokenFilter.java
  src/main/java/com/mtvs/sejong/_core/jwt/JWTTokenProvider.java
  src/main/java/com/mtvs/sejong/_core/utils/SecurityUtils.java
  src/main/java/com/mtvs/sejong/playlog/controller/PlayLogController.java
  src/main/java/com/mtvs/sejong/playlog/domain/PlayLog.java
  src/main/java/com/mtvs/sejong/playlog/repository/PlayLogRepository.java
  src/main/java/com/mtvs/sejong/playlog/service/PlayLogService.java
Labels: 🔨 Refactor, ⚙️ Setting

#14 [BugFix] SecurityConfig - h2 설정
  src/main/java/com/mtvs/sejong/_core/config/SecurityConfig.java
Labels: 🐞 BugFix

#17 [Refactor] local, 프론트 관련 설정
  src/main/java/com/mtvs/sejong/SejongApplication.java
  src/main/java/com/mtvs/sejong/_core/filter/CORSFilter.java
  src/main/java/com/mtvs/sejong/_core/jwt/JWTTokenProvider.java
  src/main/java/com/mtvs/sejong/user/controller/UserController.java
  src/main/java/com/mtvs/sejong/user/dto/UserResponseDTO.java
  src/main/java/com/mtvs/sejong/user/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor, ⚙️ Setting

#19 [Feat] PlayLog 수정
  src/main/java/com/mtvs/sejong/BaseTimeEntity.java
  src/main/java/com/mtvs/sejong/playlog/controller/PlayLogController.java
  src/main/java/com/mtvs/sejong/playlog/dto/PlayLogRequestDTO.java
  src/main/java/com/mtvs/sejong/playlog/service/PlayLogService.java
  src/test/java/com/mtvs/sejong/playlog/PlayLogServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#20 [Feat] 퀴즈 풀이 기능 구현
  src/main/java/com/mtvs/sejong/question/application/controller/RecommendController.java
  src/main/java/com/mtvs/sejong/question/application/dto/AnswerDTO.java
  src/main/java/com/mtvs/sejong/question/application/dto/AnswerSubmitRequestDTO.java
  src/main/java/com/mtvs/sejong/question/application/dto/GradingResponseDTO.java
  src/main/java/com/mtvs/sejong/question/application/dto/RecommendResponseDTO.java
  src/main/java/com/mtvs/sejong/question/domain/aggregate/Question.java
  src/main/java/com/mtvs/sejong/question/domain/service/QuestionService.java
Labels: ✨ Feature, 🔨 Refactor

#23 [Feat] Question 관련 기능 구현
  src/main/java/com/mtvs/sejong/_core/config/SecurityConfig.java
  src/main/java/com/mtvs/sejong/question/application/controller/RecommendController.java
  src/main/java/com/mtvs/sejong/question/application/dto/ChatRequestDTO.java
  src/main/java/com/mtvs/sejong/question/application/dto/ChatResponseDTO.java
  src/main/java/com/mtvs/sejong/question/application/dto/RecommendRequestDTO.java
  src/main/java/com/mtvs/sejong/question/application/dto/RecommendResponseDTO.java
  src/main/java/com/mtvs/sejong/question/domain/aggregate/Question.java
  src/main/java/com/mtvs/sejong/question/domain/service/QuestionService.java
  src/main/java/com/mtvs/sejong/question/openfeign/QuestionFeignClient.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor

#25 Feat 16
  .gitignore
  src/main/java/com/mtvs/sejong/question/application/controller/RecommendController.java
  src/main/java/com/mtvs/sejong/question/application/dto/AnswerDTO.java
  src/main/java/com/mtvs/sejong/question/application/dto/AnswerSubmitRequestDTO.java
  src/main/java/com/mtvs/sejong/question/domain/aggregate/QuizScore.java
  src/main/java/com/mtvs/sejong/question/domain/repository/QuizScoreRepository.java
  src/main/java/com/mtvs/sejong/question/domain/service/QuestionService.java
  src/main/java/com/mtvs/sejong/question/domain/service/QuizScoreService.java
Labels: ✨ Feature

#26 [Feat] 평균 퀴즈 풀이 점수 구하는 로직 추가
  src/main/java/com/mtvs/sejong/question/application/controller/RecommendController.java
  src/main/java/com/mtvs/sejong/question/application/dto/QuizScoreDTO.java
  src/main/java/com/mtvs/sejong/question/domain/repository/QuizScoreRepository.java
  src/main/java/com/mtvs/sejong/question/domain/service/QuizScoreService.java
Labels: ✨ Feature

#29 Refactor: Game 통신 시 partnerId는 partner의 Email
  src/main/java/com/mtvs/sejong/playlog/dto/GameRequestDTO.java
  src/main/java/com/mtvs/sejong/playlog/service/GameService.java
Labels: 🔨 Refactor
